ChickensAndCows:	ChickensAndCows
	g++ -Wall -g -std=c++2a -o ChickensAndCows ChickensAndCows.cpp
	./ChickensAndCows
	rm ChickensAndCows

Ascending:	Ascending.cpp
	g++ -Wall -g -std=c++2a -o Ascending Ascending.cpp
	./Ascending
	rm Ascending