ClubAdmission:	ClubAdmission.cpp
	g++ -Wall -std=c++2a -g -o ClubAdmission ClubAdmission.cpp
	./ClubAdmission

GameTable:	GameTable.cpp
	g++ -Wall -std=c++2a -g -o GameTable GameTable.cpp
	./GameTable